#@ load("@ytt:data","data")
---
apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: #@ data.values.artifactId
spec:
  vendor: terasky
  duration: #@ data.values.duration
  difficulty: #@ data.values.difficulty
  title: #@ data.values.workshopTitle
  publish:
    image: #@ "$(image_repository)/{}-workshop-files:$(workshop_version)".format(data.values.artifactId)
  workshop:
    files:
    - image:
        url:  #@ "$(image_repository)/{}-workshop-files:$(workshop_version)".format(data.values.artifactId)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
      - /templates/**
  description: #@ data.values.workshopDescription
  session:
    resources:
      memory: #@ data.values.memoryResources
    applications:
      console:
        enabled: #@ data.values.enableConsole
      docker:
        enabled: #@ data.values.enableDocker
        #@ if data.values.enableDocker:
        memory: #@ "{}Mi".format(data.values.dockerMemory)
        storage: #@ "{}Gi".format(data.values.dockerStorage)
        #@ end
      editor:
        enabled: #@ data.values.enableEditor
      registry:
        enabled: #@ data.values.enableRegistry
        #@ if data.values.enableRegistry:
        memory: #@ "{}Mi".format(data.values.registryMemory)
        storage: #@ "{}Gi".format(data.values.registryStorage)
        #@ end
      vcluster:
        enabled: #@ data.values.useVcluster
      terminal:
        enabled: #@ data.values.enableTerminal
        #@ if data.values.enableTerminal:
        layout: #@ data.values.terminalLayout
        #@ end
    namespaces:
      budget: #@ data.values.namespaceBudget
